public DbSet<AccountDetails> AccountDetails { get; set; }
public DbSet<Accounts> Accounts { get; set; }
public DbSet<AccountWithDrawals> AccountWithDrawals { get; set; }
public DbSet<AdminActivitys> AdminActivitys { get; set; }
public DbSet<AdvertisementImg> AdvertisementImg { get; set; }
public DbSet<AlipayBills> AlipayBills { get; set; }
public DbSet<BankBranchs> BankBranchs { get; set; }
public DbSet<BankTypes> BankTypes { get; set; }
public DbSet<BannerpublicityImg> BannerpublicityImg { get; set; }
public DbSet<C_Citys> C_Citys { get; set; }
public DbSet<C_Provinces> C_Provinces { get; set; }
public DbSet<ChatFriendApplications> ChatFriendApplications { get; set; }
public DbSet<ChatFriendships> ChatFriendships { get; set; }
public DbSet<ChatGroupNotices> ChatGroupNotices { get; set; }
public DbSet<ChatGroups> ChatGroups { get; set; }
public DbSet<ChatGroupUsers> ChatGroupUsers { get; set; }
public DbSet<ChatMessage> ChatMessage { get; set; }
public DbSet<Citys> Citys { get; set; }
public DbSet<Comments> Comments { get; set; }
public DbSet<CrowdFundings> CrowdFundings { get; set; }
public DbSet<Districts> Districts { get; set; }
public DbSet<Feedbacks> Feedbacks { get; set; }
public DbSet<IdentityAuthentication> IdentityAuthentication { get; set; }
public DbSet<InpourOnlineDetails> InpourOnlineDetails { get; set; }
public DbSet<InpourOnlines> InpourOnlines { get; set; }
public DbSet<JdBankTypes> JdBankTypes { get; set; }
public DbSet<MessageSetting> MessageSetting { get; set; }
public DbSet<MobileCodes> MobileCodes { get; set; }
public DbSet<MobileMessages> MobileMessages { get; set; }
public DbSet<NewBalance> NewBalance { get; set; }
public DbSet<PasswordChangeLog> PasswordChangeLog { get; set; }
public DbSet<PhoneNums> PhoneNums { get; set; }
public DbSet<Provinces> Provinces { get; set; }
public DbSet<RechargeLogs> RechargeLogs { get; set; }
public DbSet<RegisterStats> RegisterStats { get; set; }
public DbSet<RepayWays> RepayWays { get; set; }
public DbSet<ReportLists> ReportLists { get; set; }
public DbSet<SupportProjects> SupportProjects { get; set; }
public DbSet<SYS_AdminActivitys> SYS_AdminActivitys { get; set; }
public DbSet<SYS_ButtonPermissions> SYS_ButtonPermissions { get; set; }
public DbSet<SYS_MenuPermissions> SYS_MenuPermissions { get; set; }
public DbSet<SYS_MethodPermissions> SYS_MethodPermissions { get; set; }
public DbSet<SYS_RoleButtons> SYS_RoleButtons { get; set; }
public DbSet<SYS_RoleMenus> SYS_RoleMenus { get; set; }
public DbSet<SYS_RoleMethods> SYS_RoleMethods { get; set; }
public DbSet<SYS_Roles> SYS_Roles { get; set; }
public DbSet<SYS_Users> SYS_Users { get; set; }
public DbSet<SystemAccountDetails> SystemAccountDetails { get; set; }
public DbSet<SystemAccounts> SystemAccounts { get; set; }
public DbSet<SystemMessages> SystemMessages { get; set; }
public DbSet<SystemUsers> SystemUsers { get; set; }
public DbSet<SystemWithdrawLogs> SystemWithdrawLogs { get; set; }
public DbSet<TempCrowdFundingFailed> TempCrowdFundingFailed { get; set; }
public DbSet<ThirdpartyConfig> ThirdpartyConfig { get; set; }
public DbSet<ThirdPartyUsers> ThirdPartyUsers { get; set; }
public DbSet<TradePoundages> TradePoundages { get; set; }
public DbSet<UserAccounts> UserAccounts { get; set; }
public DbSet<UserActivitys> UserActivitys { get; set; }
public DbSet<UserAddressList> UserAddressList { get; set; }
public DbSet<UserDetails> UserDetails { get; set; }
public DbSet<UserLoginLog> UserLoginLog { get; set; }
public DbSet<Users> Users { get; set; }
public DbSet<UserValidates> UserValidates { get; set; }
public DbSet<WechatBill> WechatBill { get; set; }
public DbSet<WechatBillDetails> WechatBillDetails { get; set; }
public DbSet<WXPayList$> WXPayList$ { get; set; }

